import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'animate.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crud-Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className='text-center'>
          <img className='w-24' src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh9fsvH421rlb5Yx3_-g6FjPBWxZeeR_3pCVaNvYECyg&s" alt="abs-logo" />
        </div>
        {children}</body>
    </html>
  );
}
